apiVersion: v1
kind: Service
metadata:
  name: emotions-service
spec:
  selector:
    app: emotions-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http

--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotions-service
  labels:
    app: emotions-service
spec:
  selector:
    matchLabels:
      app: emotions-service
  replicas: 1
  template:
    metadata:
      labels:
        app: emotions-service
    spec:
      containers:
      - name: emotions-service
        image: emotions
        imagePullPolicy: Always
        ports:
        - containerPort: 80