apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotions-service
  labels:
    app: emotions-service
spec:
  selector:
    matchLabels:
      app: emotions-service
  replicas: 1
  template:
    metadata:
      labels:
        app: emotions-service
    spec:
      containers:
      - name: emotions-service
        image: marivr12/emotion:v11
        imagePullPolicy: Always
        ports:
        - containerPort: 3850
        env:
        - name: RABBIT_HOST 
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_CONSUMER_QUEUE
          value: "adding"
        - name: RABBIT_ALL_IMAGES_QUEUE
          value: "storage"
        - name: RABBIT_PRODUCER_QUEUE
          value: "all_data"
---
apiVersion: v1
kind: Service
metadata:
  name: emotions-service
spec:
  selector:
    app: emotions-service
  ports:
  - protocol: TCP
    port: 3850
    targetPort: http