apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: LoadBalancer
  selector:
    app: front-service
  ports:
  - protocol: TCP
    name: http
    port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  selector:
    matchLabels:
      app: front-service
  replicas: 1
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
      - name: front-service
        image: front
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: RABBIT_HOST 
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_CONSUMER_QUEUE
          value: "images"
        - name: RABBIT_PRODUCER_QUEUE
          value: "front"